<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
    </div>
    <ul class="nav navbar-nav" >
      <li><a href="#">HOME</a></li>
      <li><a href="#">SERVICES</a></li>
      <li><a href="#">ABOUT</a></li>
      <li><a href="#">REVIEWS</a></li>
      <li><a href="#">LOCATIONS</a></li>
      <li><a href="#">CONTACTS</a></li>
    </ul>
  </div>
</nav>

<img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/image1.jpg'); ?>"  /> 

<div class="images_row">
    <div class="one_image"><img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/slika1.jpg'); ?>" /> </div>
    <div class="one_image"><img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/slika2.jpg'); ?>" /> </div>
</div>
<div class="images_row">
    <div class="one_image"><img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/slika3.jpg'); ?>"  /> </div>
    <div class="one_image"><img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/slika4.jpg'); ?>"  /> </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                   <p>something to display</p>
                </div>
            </div>
        </div>
    </div>
</div>
<h1>тesting</h1>
<p>Testing for module</p>

<div id="container" class="bottom_container">
    <figure class="bottom_figure">
    <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/slikaslika2.jpg'); ?>"  />
        <figcaption class="figure_part1">Some Text</figcaption>
        <figcaption class="figure_part2">Some Text</figcaption>
    </figure>
</div>